name: "Tell Merge All to Dependabot"
description: "Tell Merge All to Dependabot"

on:
  pull_request:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  tell-merge-all-to-dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Post merge comment
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: '@dependabot merge'
            })
