name: "Tell Merge All to Dependabot"
description: "Tell Merge All to Dependabot"

on:
  pull_request:
    types: [opened, reopened]

jobs:
  tell-merge-all-to-dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Post merge comment
        run: gh pr comment ${{ github.event.pull_request.number }} --body '@dependabot merge'
        env:
          GH_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
